name: bmcp
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - ipython
  - jupyter
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - patsy
  - matplotlib
  - arviz
  - bambi
  - pymc3
  - statsmodels
  - theano-pymc
  - tensorflow
  - python-graphviz
  - pip:
      - tensorflow_probability
